# Generated by Django 5.0.6 on 2025-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_managed_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for billing', max_length=255, null=True),
        ),
    ]
