# Generated by Django 5.0.6 on 2025-11-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('cleaning_frequency_hours', models.PositiveIntegerField(help_text='How often this equipment needs cleaning (in hours). Ex: 24 for daily cleaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['facility', 'name'],
            },
        ),
    ]
