# Generated by Django 5.0.6 on 2025-11-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('facilities', '0002_facility_is_active_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for quick cleaning registration', null=True, upload_to='equipment_qrcodes/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cleaning_frequency_hours',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 hora'), (4, '4 horas'), (8, '8 horas'), (24, '24 horas'), (168, 'Semanal (168h)')], default=24, verbose_name='Frequência de limpeza (horas)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_set', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do equipamento'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de série'),
        ),
    ]
