# Generated by Django 5.0.6 on 2025-11-21 20:31

from django.db import migrations, models
import secrets


def generate_tokens_for_existing_equipment(apps, schema_editor):
    """Generate unique tokens for all existing equipment"""
    Equipment = apps.get_model('equipment', 'Equipment')
    for equipment in Equipment.objects.all():
        equipment.public_token = secrets.token_urlsafe(16)
        equipment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_equipment_qr_code_and_more'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='equipment',
            name='public_token',
            field=models.CharField(blank=True, help_text='Permanent token for QR code-based cleaning registration', max_length=32),
        ),
        # Step 2: Populate tokens for existing equipment
        migrations.RunPython(generate_tokens_for_existing_equipment, reverse_code=migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='equipment',
            name='public_token',
            field=models.CharField(blank=True, help_text='Permanent token for QR code-based cleaning registration', max_length=32, unique=True),
        ),
    ]
