# Generated by Django 5.0.6 on 2025-11-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('diagnostic', 'Diagnóstico'), ('monitoring', 'Monitoramento'), ('life_support', 'Suporte à Vida'), ('surgical', 'Cirúrgico'), ('laboratory', 'Laboratório'), ('other', 'Outro')], default='other', help_text='Categoria do equipamento', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do equipamento', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, help_text='Ex: Sala 101, Ala B, 2º andar', max_length=200, verbose_name='Localização específica'),
        ),
    ]
