# Generated by Django 5.0.6 on 2025-11-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_category_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='token_created_at',
            field=models.DateTimeField(blank=True, help_text='When the current token was generated', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='public_token',
            field=models.CharField(blank=True, help_text='Public token for QR code-based cleaning registration (expires in 5 minutes)', max_length=64, unique=True),
        ),
    ]
