# Generated by Django 5.0.6 on 2025-11-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Equipamentos, QR Code, Limpeza', max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Emoji ou classe de ícone (ex: 🔧, fa-cog)', max_length=20, verbose_name='Ícone')),
                ('description', models.TextField(blank=True, help_text='Breve descrição da categoria', verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)', verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, help_text='Exibir esta categoria na documentação', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Funcionalidade',
                'verbose_name_plural': 'Categorias de Funcionalidades',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: QR no Admin, PDF de Etiquetas', max_length=200, verbose_name='Nome da Funcionalidade')),
                ('description', models.TextField(help_text='Instruções passo a passo de como usar esta funcionalidade', verbose_name='Como Usar')),
                ('endpoint', models.CharField(blank=True, help_text='URL endpoint ou comando de gerenciamento (ex: /equipment/labels/pdf/<id>/, python manage.py ...)', max_length=300, verbose_name='Endpoint/Comando')),
                ('code_example', models.TextField(blank=True, help_text='Exemplo de código ou uso da funcionalidade', verbose_name='Exemplo de Código')),
                ('badge', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('technician', 'Technician'), ('public', 'Public'), ('security', 'Security'), ('api', 'API'), ('command', 'Command'), ('webhook', 'Webhook'), ('none', 'None')], default='none', help_text='Badge de classificação da funcionalidade', max_length=20, verbose_name='Badge')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar como funcionalidade em destaque', verbose_name='Destaque')),
                ('requires_auth', models.BooleanField(default=False, help_text='Esta funcionalidade requer autenticação', verbose_name='Requer Autenticação')),
                ('requires_permission', models.CharField(blank=True, help_text='Permissão necessária (ex: admin, manager, manager_or_admin)', max_length=100, verbose_name='Requer Permissão')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição dentro da categoria', verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, help_text='Exibir esta funcionalidade na documentação', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='documentation.featurecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
