# Generated by Django 5.0.6 on 2025-11-21 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo evidence of cleaning', upload_to='cleaning_logs/')),
                ('is_compliant', models.BooleanField(default=True, help_text='Whether this cleaning follows the required protocol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_logs', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_logs', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Cleaning Log',
                'verbose_name_plural': 'Cleaning Logs',
                'ordering': ['-cleaned_at'],
            },
        ),
    ]
