# Generated by Django 5.0.6 on 2025-11-21 19:10

import apps.cleaning_logs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaninglog',
            options={'ordering': ['-cleaned_at'], 'verbose_name': 'Registro de Limpeza', 'verbose_name_plural': 'Registros de Limpeza'},
        ),
        migrations.AlterField(
            model_name='cleaninglog',
            name='cleaned_at',
            field=models.DateTimeField(verbose_name='Data/hora da limpeza'),
        ),
        migrations.AlterField(
            model_name='cleaninglog',
            name='cleaned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleaninglog',
            name='is_compliant',
            field=models.BooleanField(default=True, verbose_name='Em conformidade'),
        ),
        migrations.AlterField(
            model_name='cleaninglog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cleaninglog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cleaning_logs.models.cleaning_photo_path, verbose_name='Foto comprobatória'),
        ),
    ]
