# Generated by Django 5.0.6 on 2025-11-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_logs', '0002_alter_cleaninglog_options_and_more'),
        ('equipment', '0004_equipment_category_equipment_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTokenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Format: equipment_id:expiry_timestamp:signature', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('expiry_minutes', models.IntegerField(default=5)),
                ('was_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('times_accessed', models.IntegerField(default=0)),
                ('generated_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tokens', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_tokens', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Temporary Token Log',
                'verbose_name_plural': 'Temporary Token Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='cleaning_lo_token_a7dc8c_idx'), models.Index(fields=['equipment', '-created_at'], name='cleaning_lo_equipme_7e0098_idx'), models.Index(fields=['expires_at'], name='cleaning_lo_expires_38c95d_idx')],
            },
        ),
    ]
